version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - /
      - /packages/app/
      - /packages/backend
    schedule:
      interval: monthly
      time: "22:00"
      timezone: America/Sao_Paulo
    target-branch: main
    # registries:
    #   - npm-codeartifact

# registries:
#   npm-codeartifact:
#       type: npm-registry
#       url: <codeartifact url>
#       username: ${{ secrets.codeartifact_username }}
#       password: ${{ secrets.codeartifact_token }}
