name: CI Workflow

# Policies run job in branches
on: 
  push: 
    branches:
      - feature/create-pipeline

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  # Workflow reference => (Monorepo - NodeJS and ReactJS) pipeline base CI
  golden_ci:
    name: "Continuous Integration"
    uses: innovats-hub/devsecops-pipelines/.github/workflows/ci.yml@feature/golden-pipeline-nodejs
    with:
      globals_package_manager: "yarn"
      globals_node_version: "20.18.2"
      job_install_deps_runner_image: "ubuntu-latest"
      job_build_app_runner_image: "ubuntu-latest"
      job_build_reusable_build_args: "yarn build:backend --config ../../app-config.yaml && yarn build:app --config ../../app-config.yaml"
