name: CI Workflow

# Policies run job in branches
on: 
  push: 
    branches:
      - feature/create-pipeline

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  # Workflow reference => (Monorepo - NodeJS and ReactJS) pipeline base CI
  golden_ci:
    name: "Continuous Integration"
    uses: innovats-hub/devsecops-pipelines/.github/workflows/ci.yml@feature/golden-pipeline-nodejs
    with:
      runner_image_job_install_deps: ubuntu-latest
      runner_image_job_build_app: ubuntu-latest
      package_manager_job_install_deps: yarn
      node_version_install_deps: 20.18.2